services:
  gzctf:
    image: gztime/gzctf:latest
    restart: always
    environment:
      - "LC_ALL=en_US.UTF-8"
    ports:
      - "8080:8080"
    volumes:
      - "./data/files:/app/files"
      - "./appsettings.json:/app/appsettings.json:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - db
      - cache

  db:
    image: postgres:alpine
    restart: always
    environment:
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - "./data/db:/var/lib/postgresql"

  cache:
    image: redis:alpine
    command: ["--bind", "0.0.0.0"]
    restart: always
